module.exports = {
  collectCoverage: true,
  collectCoverageFrom: [
    "**/src/**/*.{ts,tsx}",
    "!**/*.d.ts",
    "!**/node_modules/**",
    "!src/**/components/**/index.{js,jsx,ts,tsx}",
    "!src/**/components/**/styles.module.css",
    "!src/**/components/**/__tests__/**/*.{js,jsx,ts,tsx}",
    "!**/index.{js, ts}",
    "!**/coverage**",
    "!**/src/**/types/**",
    "!**/src/**/constants/**",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["json-summary", "text", "html", "lcov"],
  moduleFileExtensions: ["js", "jsx", "ts", "tsx"],
  moduleDirectories: ["node_modules", "src"],
  moduleNameMapper: {
    "\\.svg$": "<rootDir>/src/__mocks__/svgMock.ts",
    "\\.png$": "<rootDir>/src/__mocks__/fileMock.js",
    "\\.jpg$": "<rootDir>/src/__mocks__/fileMock.js",
    "\\.module\\.css$": "<rootDir>/src/__mocks__/styleMock.js",
    "\\.css$": "<rootDir>/src/__mocks__/styleMock.js",
    "^@/(.*)$": "<rootDir>/src/$1",
    '^features/(.*)$': '<rootDir>/src/features/$1',
  },
  preset: "ts-jest",
  setupFilesAfterEnv: ["<rootDir>/setupTests.ts"],
  testEnvironment: "jsdom",
  testPathIgnorePatterns: ["<rootDir>/node_modules/", "<rootDir>/build/"],
  transform: {
    "^.+\\.(ts|tsx)$": "ts-jest",
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
  transformIgnorePatterns: [
    "node_modules/(?!firebase)",
    "^.+\\.module\\.(css|sass|scss)$",
  ],
  verbose: true,
};
